### PR TITLE
PSR-4 namespacing

### PR DESCRIPTION
**Pull request by KoenPasman**
Not sure what your plans are for this client, but when using this as a composer dependency, there is no autoloading. I integrated autoloading and namespacing based on the PSR-4 methodology. 

This way the Client will be autoloaded when using `use PrintApi\Client`.

### CODE REVIEW

**Comment by printapi** [comment]
Thanks very much for your contribution!

We initially aimed to support PHP versions as low as 5.2.17, which lacks namespacing. After some review, we decided it's acceptable to move on to 5.3.7.

We will have to update our docs and do some testing, but intend to merge your pull request soon.

**Comment by KoenPasman** [comment]
Cool! Glad I could be of help :)

I would even say supporting everything below PHP 5.6 is unwanted, since even 5.5 is already EOL. But that's entirely up to you ofcourse ;)

**Comment by JackPoint** [comment]
As @KoenPasman says PHP < 5.6 is EOL. Would be nice if you could merge this change so we can use the namespaced version of this library.

**Comment by JackPoint** [comment]
@printapi for now only 7.3 and up are supported (see https://www.php.net/supported-versions.php) It's time to complete this PR ;)

**Comment by vincentcox** [comment]
How to use this now?
I figured the following out to install it with composer:
```
composer require printapi/printapi-php:dev-master#142f755e5ccb251cbeb0335d7fe23a5a4ce9f2de
```

Now I use in my code:
```
use PrintApi\Client;
...
public function myfunction( ... , Client $api)
{
     $api:authenticate($this->getParameter('printapi.CLIENTID'), $this->getParameter('printapi.SECRET'));
}
```

Unfortunately, it's giving me the error: "Class PrintApi\Client does not exist"

**Review by printapi — APPROVED** [review]

**Pull request merged**
